# Generated by Django 5.1 on 2024-12-17 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ownapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='Price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
