# Generated by Django 5.1 on 2024-12-17 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ownapp', '0002_car_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='Kilometer',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
