# Generated by Django 5.1 on 2024-12-25 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ownapp', '0004_category_car_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='Contactnumber',
            field=models.IntegerField(max_length=100),
        ),
    ]
