# Generated by Django 5.1 on 2024-12-25 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ownapp', '0005_alter_car_contactnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='Contactnumber',
            field=models.CharField(max_length=100),
        ),
    ]
